# Generated by Django 4.1.3 on 2024-08-19 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventType',
            field=models.CharField(choices=[('gleaning', 'Gleaning'), ('cooking', 'Cooking'), ('distribution', 'Distribution')], default='gleaning', max_length=55),
        ),
    ]
