# Generated by Django 5.0.6 on 2024-09-09 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0004_alter_member_uid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Member',
            new_name='User',
        ),
    ]
