# Generated by Django 4.1.3 on 2024-09-12 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0005_rename_member_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inventory',
            name='event',
        ),
    ]
