# Generated by Django 4.1.3 on 2024-09-12 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0008_remove_event_inventory_remove_inventory_foodtype_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='items',
            field=models.JSONField(default=list),
        ),
    ]
