# Generated by Django 4.1.3 on 2024-09-15 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0009_alter_inventory_items'),
    ]

    operations = [
        migrations.RenameField(
            model_name='signup',
            old_name='member',
            new_name='user',
        ),
    ]
