# Generated by Django 4.1.3 on 2024-09-15 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0010_rename_member_signup_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='signup',
            name='role',
        ),
    ]
