# Generated by Django 4.1.3 on 2024-09-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborsbountyapi', '0011_remove_signup_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(related_name='users', through='neighborsbountyapi.SignUp', to='neighborsbountyapi.event'),
        ),
    ]
